### ISSUE TITLE
你好，怎么下载ipynb格式的文件呢

### ISSUE THREAD

**Issue by lzwhard** [shenweichen/Coursera#1]
感谢分享

**Comment by shenweichen** [comment]
直接复制链接到下载工具里，或者clone整个仓库。。。

**Comment by bondeanikets** [comment]
Thanks for sharing buddy. You should also try "Applied text mining in python" by University of Michigan

**Comment by shenweichen** [comment]
@bondeanikets Hi,I will try it when i have time^ ^
